################################################################################
################################################################################
###
###  This file is automatically generated. Do not change this file! Changes
###  will get overwritten! Change the source file for "setup.py" instead.
###  This is either 'packageinfo.json' or 'packageinfo.jsonc'
###
################################################################################
################################################################################


from setuptools import setup

def readme():
	with open("README.md", "r", encoding="UTF-8-sig") as f:
		return f.read()

setup(
	author = "Jürgen Knauth",
	author_email = "pubsrc@binary-overflow.de",
	classifiers = [
		"Development Status :: 3 - Alpha",
		"License :: OSI Approved :: Apache Software License",
	],
	description = "This python module is a wrapper around git (= the git binary file). It is ment as a simple interface to basic git functionality.",
	download_url = "https://github.com/jkpubsrc/python-module-jk-git/tarball/0.2020.1.14",
	include_package_data = False,
	install_requires = [
		"jk_simpleexec",
	],
	keywords = [
		"git",
	],
	license = "Apache 2.0",
	name = "jk_git",
	packages = [
		"jk_git",
	],
	url = "https://github.com/jkpubsrc/python-module-jk-git",
	version = "0.2020.1.14",
	zip_safe = False,
	long_description = readme(),
	long_description_content_type="text/markdown",
)
